feat: HQM-27 sign contarct white list
haqq-network/haqq-wallet pull request #1301
Opened 2023-09-14 11:43 UTC by iGroza

Fixes #

## Proposed Changes

  - Closed: HQM-27 

## Checklist

- [x] I have read the rules of [**contribution**](https://github.com/haqq-network/haqq-wallet/blob/main/docs/contribution.md#important-steps).

2023-09-14 11:51 UTC, ragozin-nikita requested changes

2023-09-14 11:51 UTC, ragozin-nikita commented on src/debug-vars.ts
> +  disableWeb3DomainBlocking: true,
```suggestion
  disableWeb3DomainBlocking: false,
```

2023-09-14 11:51 UTC, ragozin-nikita commented on src/utils.ts
> +    request.method === EIP155_SIGNING_METHODS.ETH_SIGN_TRANSACTION ||
```suggestion
[EIP155_SIGNING_METHODS.ETH_SIGN_TRANSACTION, EIP155_SIGNING_METHODS.ETH_SEND_TRANSACTION]
.includes(request.method)
```

2023-09-14 11:51 UTC, ragozin-nikita commented on src/utils.ts
> +  if (!tx) {
```suggestion
  if (!tx || !tx.to) {
```

2023-09-14 11:51 UTC, ragozin-nikita commented on src/utils.ts
> +  if (!tx.to) {
```suggestion
```

2023-09-14 11:51 UTC, ragozin-nikita commented on src/screens/json-rpc-sign-screen.tsx
> +        info && setVerifyAddressResponse(info);
Do not create boolean variable here
```suggestion
if (info) setVerifyAddressResponse(info);
```

2023-09-15 03:00 UTC, vivalaakam approved these changes

2023-09-15 05:23 UTC, ragozin-nikita approved these changes

2023-09-15 05:28 UTC, merged