style(HQM-172): Add action button to card
haqq-network/haqq-wallet pull request #1347
Opened 2023-10-03 19:58 UTC by devkudasov

Fixes #

## Proposed Changes

- Update card layout
-
-

## Checklist

- [ ] I have read the rules of [**contribution**](https://github.com/haqq-network/haqq-wallet/blob/main/docs/contribution.md#important-steps).

2023-10-04 01:43 UTC, iGroza requested changes

2023-10-04 01:43 UTC, iGroza commented on src/components/wallet-card.tsx
> +                name="arrow_forward"
please use `IconsName` enum

2023-10-04 01:43 UTC, iGroza commented on src/components/wallet-card.tsx
> +                name="arrow_forward"
```suggestion
                name={IconsName.arrow_forward}
```

2023-10-04 08:30 UTC, ragozin-nikita approved these changes

2023-10-05 04:31 UTC, iGroza approved these changes

2023-10-05 04:43 UTC, merged