feat: browser deeplink
haqq-network/haqq-wallet pull request #1393
Opened 2023-10-20 09:28 UTC by iGroza

Fixes #

## Proposed Changes

- handle deeplink to open browser

https://github.com/haqq-network/haqq-wallet/assets/25716589/5c511860-c80b-4983-b450-7ae016f77336

## Checklist

- [x] I have read the rules of [**contribution**](https://github.com/haqq-network/haqq-wallet/blob/main/docs/contribution.md#important-steps).

2023-10-23 07:10 UTC, iGroza commented
wait for @VorobevSA approve

2023-10-24 06:54 UTC, devkudasov requested changes

2023-10-24 06:54 UTC, devkudasov commented on src/event-actions/on-deep-link.ts
> +    if (link.startsWith('haqq://browser')) {
Make sense to move it into const

2023-10-24 06:54 UTC, devkudasov commented on src/event-actions/on-deep-link.ts
> +    if (link.startsWith('haqq://web3browser')) {
You can use const here as well

2023-10-24 06:54 UTC, devkudasov commented on src/event-actions/on-deep-link.ts
>      if (link.startsWith('haqq://wc')) {
Many different url prefixes. Maybe better use enum instead of consts?

2023-10-26 12:54 UTC, devkudasov approved these changes

2023-10-26 13:00 UTC, merged