feat: return of custom provider
haqq-network/haqq-wallet pull request #1461
Opened 2023-11-10 11:55 UTC by vivalaakam

## Proposed Changes

- return of custom provider

## Checklist

- [x] I have read the rules of [**contribution**](https://github.com/haqq-network/haqq-wallet/blob/main/docs/contribution.md#important-steps).

2023-11-10 11:56 UTC, iGroza approved these changes

2023-11-13 19:54 UTC, devkudasov approved these changes

2023-11-15 12:59 UTC, ragozin-nikita requested changes

2023-11-15 12:59 UTC, ragozin-nikita commented on e2e/6_sss.test.ts
> +  let isAndroid = device.getPlatform() === 'android';
```suggestion
  const isAndroid = device.getPlatform() === 'android';
```

2023-11-15 12:59 UTC, ragozin-nikita commented on e2e/6_sss.test.ts
> +    isAndroid = device.getPlatform() === 'android';
```suggestion
```

2023-11-15 12:59 UTC, ragozin-nikita commented on e2e/6_sss.test.ts
> +    // await getCoins(mnemonic);
Unused code

2023-11-15 12:59 UTC, ragozin-nikita commented on index.js
> +LogBox.ignoreAllLogs();
```suggestion
```

2023-11-15 12:59 UTC, ragozin-nikita commented on package.json
> +    "detox:ios:build": "detox build --configuration ios.sim.debug",
```suggestion
    "detox:ios:build": "detox build --configuration ios.sim.release",
```

2023-11-15 12:59 UTC, ragozin-nikita commented on package.json
> +    "detox:ios:test": "detox test --configuration ios.sim.debug --loglevel warn --cleanup --record-videos failing --take-screenshots failing --retries 2",
```suggestion
    "detox:ios:test": "detox test --configuration ios.sim.release --loglevel warn --cleanup --record-videos failing --take-screenshots failing --retries 2",
```

2023-11-15 12:59 UTC, ragozin-nikita commented on src/components/browser-privacy-details.tsx
> +
```suggestion
```

2023-11-16 03:45 UTC, vivalaakam commented on e2e/6_sss.test.ts
> +    // await getCoins(mnemonic);
used later

2023-11-24 07:50 UTC, ragozin-nikita requested changes

2023-11-24 07:50 UTC, ragozin-nikita commented on index.js
> +// LogBox.ignoreLogs(['Warning: ...']);
Unused code

2023-11-24 07:50 UTC, ragozin-nikita commented on src/components/nft-collection-details.tsx
> +
```suggestion
```

2023-11-24 07:50 UTC, ragozin-nikita commented on src/components/signin-networks/signin-networks.tsx
> +    () => isApple || isGoogle || isCustom,
Seems like this is excessive memoization

2023-11-24 07:50 UTC, ragozin-nikita commented on src/services/provider-sss.ts
> +  if (!verifier) {
Maybe you should check this at the beginning of this function?

2023-11-24 07:50 UTC, ragozin-nikita commented on src/variables/sss.ts
> +  [SssProviders.custom]: 'iCloud or Google Drive',
I think we should place newline at the beginning and add small adjustment to the name
```suggestion
  [SssProviders.custom]: '\nHAQQ Provider',
```

2024-01-04 06:12 UTC, ragozin-nikita requested changes

2024-01-04 06:12 UTC, ragozin-nikita commented on src/types/url-parse.d.ts
> +
```suggestion

```

2024-01-04 06:12 UTC, ragozin-nikita commented on src/services/logger.ts
> +  private _emodji?: string;
Why this was moved?

2024-01-04 09:50 UTC, ragozin-nikita approved these changes

2024-01-04 09:55 UTC, merged