feat: New errors handling
haqq-network/haqq-wallet pull request #1592
Opened 2023-12-27 10:08 UTC by devkudasov

Fixes #

## Proposed Changes

<img width="465" alt="Screenshot 2023-12-27 at 13 03 58" src="https://github.com/haqq-network/haqq-wallet/assets/16937939/547d2dd1-9d2e-4dd2-b7e4-0db9006c1c3c">

## Checklist

- [ ] I have read the rules of [**contribution**](https://github.com/haqq-network/haqq-wallet/blob/main/docs/contribution.md#important-steps).

2023-12-27 10:25 UTC, ragozin-nikita requested changes

2023-12-27 10:25 UTC, ragozin-nikita commented on package.json
> +    "react-native-toast-message": "^2.2.0",
Fix the version please

2023-12-28 08:15 UTC, devkudasov commented on package.json
> +    "react-native-toast-message": "^2.2.0",
Done

2023-12-28 08:16 UTC, ragozin-nikita approved these changes

2024-01-04 18:36 UTC, merged