refactor(SettingsAcountEdit): code
haqq-network/haqq-wallet pull request #527
Opened 2022-12-01 06:41 UTC by samandarkuchkarov

Fixes #386 

## Proposed Changes

-Change the imports to absolute:
-Move text to i18n
-Change the colors from the constants to similar ones in Color
-Transferring the screen logic to components
-Replace navigation hooks with typed navigation hooks in folder src/hooks

## Checklist

- [ ] I have read the rules of [**contribution**](https://github.com/haqq-network/haqq-mobile/blob/main/docs/contribution.md#important-steps).

2022-12-01 17:42 UTC, gHashTag commented on src/components/settings-account-edit.tsx
> +                <Icon i24 name="close_circle" color={LIGHT_GRAPHIC_BASE_2} />
Change color prop
```jsx
color={Color.graphicBase2}
```

2022-12-01 17:54 UTC, gHashTag commented on src/components/settings-account-edit.tsx
> +import {LIGHT_GRAPHIC_BASE_2, LIGHT_GRAPHIC_GREEN_1} from '@app/variables';
Use `Color` enum for support dark theme

2022-12-01 17:54 UTC, gHashTag requested changes
Try to make the `<CustomHeader />` call the `getText` and `getColor` methods in itself.
As for example, `<Text/>` already does

2022-12-02 06:35 UTC, samandarkuchkarov commented on src/components/settings-account-edit.tsx
> +import {LIGHT_GRAPHIC_BASE_2, LIGHT_GRAPHIC_GREEN_1} from '@app/variables';
done

2022-12-02 11:01 UTC, gHashTag approved these changes

2022-12-03 13:00 UTC, vivalaakam commented on src/components/actions-sheet/index.android.tsx
>            </Text>
```suggestion
          <Text t14 style={styles.t8} i18n={I18N.actionSheetMessage} />
```

2022-12-03 13:01 UTC, vivalaakam commented on src/components/actions-sheet/index.android.tsx
> +            <Text color={LIGHT_TEXT_BLUE_1} t14 style={styles.tButton}>
i18n prop can be used

2022-12-04 04:48 UTC, samandarkuchkarov commented on src/components/actions-sheet/index.android.tsx
> +import {createTheme} from './../../helpers/create-theme';
done

2022-12-04 04:48 UTC, samandarkuchkarov commented on src/components/actions-sheet/index.android.tsx
> +            <Text color={Color.graphicRed1} t14 style={styles.tButton}>
done

2022-12-04 04:49 UTC, samandarkuchkarov commented on src/components/actions-sheet/index.android.tsx
> +            <Text color={LIGHT_TEXT_BLUE_1} t14 style={styles.tButton}>
done

2022-12-04 04:49 UTC, samandarkuchkarov commented on src/components/actions-sheet/index.android.tsx
>            </Text>
done

2022-12-05 08:23 UTC, vivalaakam approved these changes

2022-12-05 09:50 UTC, merged