refactor (settings-accounts): code
haqq-network/haqq-wallet pull request #530
Opened 2022-12-01 11:10 UTC by samandarkuchkarov

Fixes #388 

## Proposed Changes

-Change the imports to absolute:
-Move text to i18n
-Change the colors from the constants to similar ones in Color
-Transferring the screen logic to components
-Replace navigation hooks with typed navigation hooks in folder src/hooks

## Checklist

- [ ] I have read the rules of [**contribution**](https://github.com/haqq-network/haqq-wallet/blob/main/docs/contribution.md#important-steps).

2022-12-01 17:28 UTC, gHashTag commented on src/components/settings-accounts.tsx
> +          color={getColor(Color.textSecond1)}
`сolor={Color.textSecond1}`

2022-12-01 17:34 UTC, gHashTag commented on src/components/wallet-row.tsx
> +  const pressCard = () => {
Can be written in 1 line

2022-12-01 17:36 UTC, gHashTag commented on src/screens/settings-accounts.tsx
> +import {useTypedNavigation} from '@app/hooks';
use one import for hooks

2022-12-02 10:05 UTC, samandarkuchkarov commented on src/components/wallet-row.tsx
> +  const pressCard = () => {
done

2022-12-02 10:05 UTC, samandarkuchkarov commented on src/components/settings-accounts.tsx
> +          color={getColor(Color.textSecond1)}
done

2022-12-04 04:58 UTC, samandarkuchkarov commented on src/screens/settings-accounts.tsx
> +import {useTypedNavigation} from '@app/hooks';
done

2022-12-06 11:42 UTC, gHashTag requested changes
Fix comment

2022-12-07 13:39 UTC, samandarkuchkarov commented on src/screens/settings-accounts.tsx
>  import {useWallets} from '@app/hooks';
done

2022-12-08 11:13 UTC, merged