refactor(SettingsFaq): code
haqq-network/haqq-wallet pull request #537
Opened 2022-12-02 11:08 UTC by samandarkuchkarov

Fixes #

## Proposed Changes

  -Change the imports to absolute:

## Checklist

- [ ] I have read the rules of [**contribution**](https://github.com/haqq-network/haqq-wallet/blob/main/docs/contribution.md#important-steps).

2022-12-03 07:28 UTC, samandarkuchkarov commented
CustomHeader is changed in settingsAdressBook

2022-12-03 07:31 UTC, samandarkuchkarov commented
CustomHeader is changed in settingsAccountEdit task

2022-12-05 13:06 UTC, samandarkuchkarov commented on src/i18n.ts
> +  settingsContactEditDelete,
done

2022-12-06 11:39 UTC, gHashTag commented on src/i18n.ts
> +  settingsContactEditSure,
I meant that the enumeration should go in alphabetical order
<img width="154" alt="image" src="https://user-images.githubusercontent.com/6774813/205901300-bc6f4ef4-ae0e-45da-a292-35cbaed97666.png">
And in `en` object
<img width="284" alt="image" src="https://user-images.githubusercontent.com/6774813/205901910-1470013d-f31a-479c-b411-46778492671f.png">

2022-12-06 11:40 UTC, gHashTag requested changes
Fix i18n orders

2022-12-08 11:14 UTC, vivalaakam commented on src/screens/settings-contact-edit.tsx
> +    const DelateContact = getText(I18N.settingsContactEditDeleteContact);
variables in camelCase pls

2022-12-09 10:08 UTC, merged

2022-12-09 10:39 UTC, samandarkuchkarov commented on src/screens/settings-contact-edit.tsx
> +    const DelateContact = getText(I18N.settingsContactEditDeleteContact);
done