refactor: transaction-sum-address
haqq-network/haqq-wallet pull request #542
Opened 2022-12-03 06:52 UTC by samandarkuchkarov

Fixes #412 

## Proposed Changes

  -Change the imports to absolute:
  -Change the colors from the constants to similar ones in Color
  -Replace svg icons with icon icons.

## Checklist

- [ ] I have read the rules of [**contribution**](https://github.com/haqq-network/haqq-wallet/blob/main/docs/contribution.md#important-steps).

2022-12-06 11:23 UTC, gHashTag commented on src/components/transaction-address.tsx
> +                  style={page.icon}
Use i24(by design) and remove `icon` style

2022-12-06 11:24 UTC, gHashTag commented on src/components/transaction-address.tsx
> +                  style={page.icon}
And rename `page` to `style`

2022-12-06 11:28 UTC, gHashTag requested changes
Fix comments

2022-12-08 11:16 UTC, vivalaakam commented on src/components/list-contact.tsx
> +      ListFooterComponent={listFooterComponentRender}
that difference with previous version?

2022-12-08 11:16 UTC, vivalaakam approved these changes

2022-12-09 06:08 UTC, merged