refactor(SettingsSecurityPin): code
haqq-network/haqq-wallet pull request #554
Opened 2022-12-05 11:45 UTC by Crazy-MIXER

- Transferring the screen logic to components
 - Move text to i18n
 - Replace navigation hook
 **corrected**: delete `setPin('')` from the match check the first pin code and the second pin code

2022-12-06 11:05 UTC, gHashTag commented on src/components/settings-security-pin/settings-security-pin.tsx
> +        showModal(getText(I18N.settingsSecurityPinLoading));
Translations are not needed here, because this is the name of the Modal that identifies

2022-12-06 11:07 UTC, gHashTag requested changes
Fix comment please

2022-12-07 11:19 UTC, gHashTag approved these changes

2022-12-08 05:24 UTC, vivalaakam approved these changes

2022-12-09 03:42 UTC, merged