refactor code
haqq-network/haqq-wallet pull request #556
Opened 2022-12-05 15:22 UTC by Crazy-MIXER

2022-12-05 15:25 UTC, Crazy-MIXER commented
- Move text to i18n
- Replace navigation hooks
- Change the imports to absolute

2022-12-06 10:59 UTC, gHashTag commented on src/components/restore-agreement/restore-agreement.tsx
> +        color={getColor(Color.textBase2)}
```jsx
color={Color.textBase2}
```

2022-12-06 11:00 UTC, gHashTag requested changes
Fix comment

2022-12-06 14:49 UTC, Crazy-MIXER commented on src/components/restore-agreement/restore-agreement.tsx
> +        color={getColor(Color.textBase2)}
fix it

2022-12-08 05:29 UTC, merged