refactor(SigninRestoreWallet): code
haqq-network/haqq-wallet pull request #563
Opened 2022-12-06 16:33 UTC by Crazy-MIXER

- Transferring the screen logic to components
- Move text to i18n
- Replace navigation hooks
- Change the import to absolute

2022-12-07 11:07 UTC, gHashTag commented on src/components/singin-restore-wallet/singin-restore-wallet.tsx
> +  const onDone = useCallback(() => {
Move method to screen level

2022-12-07 11:07 UTC, gHashTag requested changes
Fix comment

2022-12-09 10:58 UTC, gHashTag commented on src/screens/signin-restore-wallet.tsx
> +  const [seed, setSeed] = useState('');
Move this into component

2022-12-09 11:00 UTC, gHashTag commented on src/screens/signin-restore-wallet.tsx
> +  const onDoneTry = () => {
To use the state in a component
 ```js
const onDoneTry = (seed: string) => {
```

2022-12-09 11:00 UTC, gHashTag commented on src/screens/signin-restore-wallet.tsx
> +  const route = useTypedRoute<'restorePhrase'>();
use destructurization

2022-12-09 11:01 UTC, gHashTag requested changes
Fix comments

2022-12-09 20:47 UTC, Crazy-MIXER commented
wait correction in src/i18n.ts to correctly resolve conflicts

2022-12-10 15:22 UTC, gHashTag commented on src/screens/signin-restore-wallet.tsx
> +  const route = useTypedRoute<'restorePhrase'>();
not done now

2022-12-10 19:17 UTC, Crazy-MIXER commented on src/screens/signin-restore-wallet.tsx
> +  const route = useTypedRoute<'restorePhrase'>();
Sorry, done now

2022-12-11 04:52 UTC, gHashTag approved these changes

2022-12-11 04:55 UTC, vivalaakam approved these changes

2022-12-11 06:17 UTC, merged