refactor(SettingsProvider): code
haqq-network/haqq-wallet pull request #577
Opened 2022-12-08 11:06 UTC by samandarkuchkarov

Fixes #393 

## Proposed Changes

  -Change the imports to absolute:
  -Change the colors from the constants to similar ones in Color
![Simulator Screen Shot - iPhone 14 - 2022-12-08 at 16 01 11](https://user-images.githubusercontent.com/70755860/206431345-642a2713-1e7b-4753-9c53-7dcd39cc9401.png)

## Checklist

- [x] I have read the rules of [**contribution**](https://github.com/haqq-network/haqq-wallet/blob/main/docs/contribution.md#important-steps).

2022-12-09 10:43 UTC, gHashTag commented on src/components/ui/data-content.tsx
> +import {Text} from '@app/components/ui/text';
```suggestion
import {Text} from '@app/components/ui';
```

2022-12-09 10:44 UTC, gHashTag requested changes
Pls accept suggestion

2022-12-10 14:58 UTC, gHashTag approved these changes

2022-12-10 17:44 UTC, vivalaakam approved these changes

2022-12-11 05:02 UTC, gHashTag approved these changes

2022-12-11 07:11 UTC, vivalaakam requested changes
revert [ios/haqq/haqq.entitlements](https://github.com/haqq-network/haqq-wallet/pull/577/files#diff-d277b486442c6aa3b3a287d2d3d118dd187b9eb1325321010173170cc4f7904e)

2022-12-11 08:36 UTC, vivalaakam commented on src/screens/.eslintignore
> +haqq.entitlements
Why it there? Enough in the root

2022-12-11 09:05 UTC, samandarkuchkarov commented on src/screens/.eslintignore
> +haqq.entitlements
ok removing

2022-12-11 09:40 UTC, vivalaakam commented
Are you sure that you remove right file?)

2022-12-11 10:36 UTC, vivalaakam approved these changes

2022-12-11 11:10 UTC, merged