refactor(signupAgreement): code
haqq-network/haqq-wallet pull request #593
Opened 2022-12-10 06:41 UTC by sleepy-corpse

Fixes #

## Proposed Changes

  - Changed imports to absolute
  - Added typed navigation

## Checklist

- [ ] I have read the rules of [**contribution**](https://github.com/haqq-network/haqq-wallet/blob/main/docs/contribution.md#important-steps).

2022-12-10 13:33 UTC, gHashTag requested changes
You also need to refactor `create-agreement` component

2022-12-11 06:59 UTC, gHashTag commented on src/components/create-agreement/create-agreement.tsx
> +import {createTheme, windowHeight, windowWidth} from '@app/helpers';
Use `useWindowDimensions` hook

2022-12-11 06:59 UTC, gHashTag requested changes
Fix comments and use destructurization in `src/screens/signup-agreement.tsx`
```js
const {nextScreen} = useTypedRoute<'createAgreement'>().params;
```

2022-12-11 16:09 UTC, gHashTag approved these changes

2022-12-11 16:42 UTC, gHashTag approved these changes

2022-12-12 04:38 UTC, vivalaakam approved these changes

2022-12-12 06:27 UTC, merged