refactor(transactionAccounts): code
haqq-network/haqq-wallet pull request #595
Opened 2022-12-10 10:02 UTC by samandarkuchkarov

Fixes #405 

## Proposed Changes

-Change the imports to absolute:
-Move text to i18n
-Transferring the screen logic to components
-Replace navigation hooks with typed navigation hooks in folder src/hooks

## Checklist

- [ ] I have read the rules of [**contribution**](https://github.com/haqq-network/haqq-wallet/blob/main/docs/contribution.md#important-steps).

2022-12-10 13:22 UTC, gHashTag approved these changes

2022-12-10 13:23 UTC, gHashTag commented on src/screens/transaction-account.tsx
>    const wallets = useWallets();
Look and use `useWalletsList` hook

2022-12-10 13:23 UTC, gHashTag requested changes
useWalletsList

2022-12-10 16:39 UTC, samandarkuchkarov commented on src/screens/transaction-account.tsx
>    const wallets = useWallets();
done

2022-12-11 04:18 UTC, gHashTag approved these changes

2022-12-11 04:46 UTC, vivalaakam approved these changes

2022-12-11 04:56 UTC, merged